### ISSUE TITLE
消费者的监听不起作用

### ISSUE THREAD

**Issue by f497196689** [aqlu/rocketmq-demo#1]
两个项目都跑起来以后，消费者里面的代码都不执行呀……

**Comment by f497196689** [comment]
在ConsumerApplication注入RocketMQTemplate就好了，如图所示。
![image](https://user-images.githubusercontent.com/15325854/38004238-e4694df8-326d-11e8-941a-93917493f214.png)

**Comment by aqlu** [comment]
rocketmq用的那个版本？日志或异常信息提供下

**Comment by aqlu** [comment]
消费者是不需要注入RocketMQTemplate的

**Comment by f497196689** [comment]
rocketmq版本为3.2.4，日志只有以下内容，无法消费信息
![image](https://user-images.githubusercontent.com/15325854/38007782-b1a4ebec-327d-11e8-8a4c-a0c16ae6f1ed.png)

**Comment by aqlu** [comment]
demo有修改过吗？从日志看监听器都已启动了。

**Comment by kmlkirito** [comment]
我用也是消费者的监听不起作用
