### ISSUE TITLE
请问有rpc调用的例子吗？

### ISSUE THREAD

**Issue by JamesXiao** [aqlu/rocketmq-demo#2]
demo跑通了，展示的场景是producer发送消息，然后consumer接收消息打印，这个场景下producer只知道自己的消息发出去了，不关心consumer是谁，收到没，以及有何处理结果。

我想请问，对于请求--响应的业务场景，有没有示例代码？即A以生产者角色发出消息(比如一个查询请求)，B以消费者角色收到请求后，需要把查询结果返回给A，这时候B就变成了生产者，A成了消费者。
一来一回两个消息，还要做消息id的配对，感觉会有点绕，写业务的地方如果还要关心这个，就比较麻烦了。

谢谢

**Comment by aqlu** [comment]
不能直接做接口异步调用吗？这种场景感觉不需要MQ。

**Comment by JamesXiao** [comment]
好的，那还是用dubbo之类的框架来做，thx
