### ISSUE TITLE
依赖包下载不下来，这个可能是啥原因呀

### ISSUE THREAD

**Issue by neatlife** [aqlu/rocketmq-demo#4]
[ERROR] Failed to execute goal on project rocketmq-produce-demo: Could not resolve dependencies for project com.aqlu:rocketmq-produce-demo:jar:1.0.0-SNAPSHOT: Could not find artifact org.apache.rocketmq:spring-boot-starter-rocketmq:jar:1.0.0-SNAPSHOT -> [Help 1]

**Comment by aqlu** [comment]
请参考README.md，写此Demo时`spring-boot-starter-rocketmq`项目还处于内部测试中，所以依赖的版本可能不对。

> Note:
>
> if `org.apache.rocketmq:spring-boot-starter-rocketmq:1.0.0-SNAPSHOT` not exists in maven central repository, before you run this demo, you must download [spring-boot-starter-rocketmq](https://github.com/apache/rocketmq-externals/tree/master/rocketmq-spring-boot-starter) and use `mvn clean install` build it by self.

**Comment by neatlife** [comment]
@aqlu 好的
